export type TrialType = Partial<{
  "NCT Number": string;
  "Study Title": string;
  "Study URL": string;
  Acronym: string;
  "Study Status": "RECRUITING" | "WITHDRAWN" | "NOT_YET_RECRUITING" | string;
  "Brief Summary": string;
  "Study Results": "NO" | "YES";
  Conditions: string;
  Interventions: string;
  "Primary Outcome Measures": string;
  "Secondary Outcome Measures": string;
  "Other Outcome Measures": string;
  Sponsor: string;
  Collaborators: string;
  Sex: "FEMALE" | "MALE" | "ALL";
  Age: string;
  Phases: "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4" | string;
  Enrollment: number | string;
  "Study Type": string;
  "Study Design": string;
  "Funder Type": string;
  "Other IDs": string | number;
  "Start Date": string;
  "Primary Completion Date": string;
  "Completion Date": string;
  "First Posted": string;
  "Results First Posted": string;
  "Last Update Posted": string;
  Locations: string;
  "Study Documents": string;
}>;
