import { PhysicianType } from "./types";

export const Physicians: PhysicianType[] = [
  {
    status: "Active",
    lastName: "Zahabi",
    firstName: "Fehmida",
    title: "Dr",
    degree: "MD",
    gender: "F",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "English",
    secondLanguage: "",
    regLicenseNumber: "K1736",
    expirationDate: "",
    npiNumber: "1740397603",
    taxonomy: "207RR0500X",
    primarySpecialty: "Rheumatology",
    boardCertified: "",
    secondSpecialty: "Internal Medicine",
    firstResearchInterest: "Rheumatoid Arthritis",
    secondResearchInterest: "Autoimmune",
    thirdResearchInterest: "Lupus",
    notes:
      'An internist who treats diseases of joints, muscle, bones and tendons. This specialist diagnoses and treats arthritis, back pain, muscle strains, common athletic injuries and "collagen" diseases.',
  },
  {
    status: "Active",
    lastName: "Rishikesh",
    firstName: "Ranjitha",
    title: "",
    degree: "MD",
    gender: "F",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "English",
    secondLanguage: "",
    regLicenseNumber: "P0665",
    expirationDate: "",
    npiNumber: "1396985180",
    taxonomy: "207R00000X",
    primarySpecialty: "Internal Medicine",
    boardCertified: "Yes",
    secondSpecialty: "Primary Care",
    firstResearchInterest: "Weight Loss",
    secondResearchInterest: "Hypertension",
    thirdResearchInterest: "COPD",
    notes:
      "We offer expert care for chronic conditions such as high blood pressure, cholesterol issues, thyroid disorders, asthma, COPD, depression, and ADHD.",
  },
  {
    status: "Active",
    lastName: "Aligeti",
    firstName: "Venkata Ramana",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "English",
    secondLanguage: "",
    regLicenseNumber: "P3604",
    expirationDate: "",
    npiNumber: "1093731267",
    taxonomy: "207RC0000X",
    primarySpecialty: "Cardiology",
    boardCertified: "Yes",
    secondSpecialty: "",
    firstResearchInterest: "Hypertension",
    secondResearchInterest: "Hypercholesterolemia",
    thirdResearchInterest: "Arrhythmia",
    notes:
      "Conditions Treated: Congestive Heart Failure, Chest Pain, Heart Attack, High Blood Presuure, Coronary Artery Disease, Atrial Fibrillation, Valvular-Disease, Peripheral Artery Disease, Varicose Veins, Abdominal Aortic Aneurysms, Carotid Artery Disease, Stroke Prevention",
  },
  {
    status: "Active",
    lastName: "Noyes",
    firstName: "Chris",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "English",
    secondLanguage: "",
    regLicenseNumber: "L3772",
    expirationDate: "",
    npiNumber: "1205803400",
    taxonomy: "207Q00000X",
    primarySpecialty: "Family Medicine",
    boardCertified: "",
    secondSpecialty: "",
    firstResearchInterest: "Weight Loss",
    secondResearchInterest: "Cancer Screening",
    thirdResearchInterest: "Diabetes",
    notes:
      "Management of Acute & Chronic Illness:  Diabetes, Obesity, Hypothyroidism, High Blood Pressure – hypertension, High Cholesterol – hyperlipidemia, Hormone Deficiencies – low testosterone and menopause, Asthma, Allergies, Arthritis, Anxiety Disorders, Depression \n\nCardiac Imaging: Stress Tests, Carotid Ultrasounds, Echocardiograms, Extremity Arterial Dopplers, Screening for Abdominal Aortic Aneurysms \n\nLab Services: In-office Labcorp Phlebotomist, Rapid Testing for Flu, Strep, Mono, Covid, RSV, UTIs, Pregnancy, Urinalysis ",
  },
  {
    status: "Active",
    lastName: "Parisi",
    firstName: "Michael",
    title: "",
    degree: "DO",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "English",
    secondLanguage: "",
    regLicenseNumber: "K3381",
    expirationDate: "",
    npiNumber: "1447228713",
    taxonomy: "207R00000X",
    primarySpecialty: "Family Medicine",
    boardCertified: "",
    secondSpecialty: "Adult Medicine",
    firstResearchInterest: "Weight Loss",
    secondResearchInterest: "Cancer Screening",
    thirdResearchInterest: "Diabetes",
    notes:
      "Management of Acute & Chronic Illness:  Diabetes, Obesity, Hypothyroidism, High Blood Pressure – hypertension, High Cholesterol – hyperlipidemia, Hormone Deficiencies – low testosterone and menopause, Asthma, Allergies, Arthritis, Anxiety Disorders, Depression \n\nCardiac Imaging: Stress Tests, Carotid Ultrasounds, Echocardiograms, Extremity Arterial Dopplers, Screening for Abdominal Aortic Aneurysms \n\nLab Services: In-office Labcorp Phlebotomist, Rapid Testing for Flu, Strep, Mono, Covid, RSV, UTIs, Pregnancy, Urinalysis ",
  },
  {
    status: "Active",
    lastName: "Tesic",
    firstName: "Goran",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "125715",
    expirationDate: "",
    npiNumber: "1174802334",
    taxonomy: "208600000X",
    primarySpecialty: "Surgery",
    boardCertified: "",
    secondSpecialty: "Vascular Surgery",
    firstResearchInterest: "Peripheral Artery Disease",
    secondResearchInterest: "Vascular Surgery",
    thirdResearchInterest: "Aortic Aneurysim",
    notes:
      "Offers treatment for the following: Aortic or other Aneurysms,\nCarotid Stenosis, TIA or Stroke (CAD), Chronic Venous Insufficiency (CVI), Claudication or Leg Ischemia, Deep Venous Thrombosis (DVT), \nDialysis Access Evaluation, IVC Filter Evaluation, Leg Pain or Swelling, \nMesenteric Ischemia, Non-healing Wound Care, Peripheral Artery Disease (PAD), Renal Artery Stenosis, Spider Veins, Temporal Arteritis, \nVaricose Veins.",
  },
  {
    status: "Active",
    lastName: "Yau",
    firstName: "Franklin",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "K2829",
    expirationDate: "",
    npiNumber: "1295764033",
    taxonomy: "2086S0129X",
    primarySpecialty: "Vascular Surgery",
    boardCertified: "",
    secondSpecialty: "Surgery",
    firstResearchInterest: "Peripheral Artery Disease",
    secondResearchInterest: "Vascular Surgery",
    thirdResearchInterest: "Aortic Aneurysim",
    notes:
      "Offers treatment for the following: Aortic or other Aneurysms,\nCarotid Stenosis, TIA or Stroke (CAD), Chronic Venous Insufficiency (CVI), Claudication or Leg Ischemia, Deep Venous Thrombosis (DVT), \nDialysis Access Evaluation, IVC Filter Evaluation, Leg Pain or Swelling, \nMesenteric Ischemia, Non-healing Wound Care, Peripheral Artery Disease (PAD), Renal Artery Stenosis, Spider Veins, Temporal Arteritis, \nVaricose Veins.",
  },
  {
    status: "Active",
    lastName: "Anwar",
    firstName: "Mohammad Faizan",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "25MA09841700",
    expirationDate: "",
    npiNumber: "1104263722",
    taxonomy: "207R00000X",
    primarySpecialty: "Internal Medicine",
    boardCertified: "Yes",
    secondSpecialty: "",
    firstResearchInterest: "Weight Loss",
    secondResearchInterest: "Hypertension",
    thirdResearchInterest: "COPD",
    notes:
      "We offer expert care for chronic conditions such as high blood pressure, cholesterol issues, thyroid disorders, asthma, COPD, depression, and ADHD.",
  },
  {
    status: "Pending",
    lastName: "Pratt",
    firstName: "Steven",
    title: "Dr",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Internal Medicine",
    boardCertified: "",
    secondSpecialty: "Primary Care",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
  {
    status: "Pending",
    lastName: "Marsh",
    firstName: "Coly",
    title: "",
    degree: "OD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Opthalmology",
    boardCertified: "",
    secondSpecialty: "",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
  {
    status: "Pending",
    lastName: "Nawaz",
    firstName: "M. Zaim",
    title: "",
    degree: "MD",
    gender: "F",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Cardiology",
    boardCertified: "",
    secondSpecialty: "Vascular Surgery",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
  {
    status: "Pending",
    lastName: "Shah",
    firstName: "Zille Huma",
    title: "",
    degree: "MD",
    gender: "F",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Family Medicine",
    boardCertified: "",
    secondSpecialty: "",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
  {
    status: "Pending",
    lastName: "Chavda",
    firstName: "Chirag",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Primary Care",
    boardCertified: "",
    secondSpecialty: "",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
  {
    status: "Pending",
    lastName: "Ibrahim",
    firstName: "Saquib",
    title: "",
    degree: "MD",
    gender: "M",
    practiceName: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    phone: "",
    fax: "",
    cell: "",
    email: "",
    language: "",
    secondLanguage: "",
    regLicenseNumber: "",
    expirationDate: "",
    npiNumber: "",
    taxonomy: "",
    primarySpecialty: "Family Medicine",
    boardCertified: "",
    secondSpecialty: "",
    firstResearchInterest: "",
    secondResearchInterest: "",
    thirdResearchInterest: "",
    notes: "",
  },
];
